### ISSUE TITLE
Show warning for bad sym linked files instead of stopping process

### ISSUE THREAD

**Issue by bostrt** [hokuda/pcore#5]
If I have a bad link in my modules directory while running pcore, it stops the process and prints an error about the bad link. It would be great if pcore would record that warning to logs and continue on gathering data. Below is an example exception:

```
...
2016-01-29 16:41:26,458 229 INFO copying /opt/jboss-ews-2.0/httpd/modules/mod_setenvif.so to pcore-2016-01-29-16.41.25//opt/jboss-ews-2.0/httpd/modules
2016-01-29 16:41:26,459 229 INFO copying /opt/jboss-ews-2.0/httpd/modules/mod_auth_kerb.so to pcore-2016-01-29-16.41.25//opt/jboss-ews-2.0/httpd/modules
Traceback (most recent call last):
  File "./pcore", line 507, in <module>
    main()
  File "./pcore", line 489, in main
    copy_libs(libs)
  File "./pcore", line 459, in copy_libs
    map(copy, libs)
  File "./pcore", line 232, in copy
    shutil.copy(file, copydir)
  File "/usr/lib64/python2.6/shutil.py", line 84, in copy
    copyfile(src, dst)
  File "/usr/lib64/python2.6/shutil.py", line 50, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/opt/jboss-ews-2.0/httpd/modules/mod_auth_kerb.so'
```

After the error above, pcore stops.

**Comment by hokuda** [comment]
Robert, thank you very much for the report!
